version: '3.7'
services:
  websocket1:
    build:
      context: ./websocket
    environment:
      - SERVER_NAME=the_first
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8081:8081'
    networks:
      - backend1
  websocket2:
    build:
      context: ./websocket
    environment:
      - SERVER_NAME=the_second
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8082:8081'
    networks:
      - backend1
  nginx:
    image: 'nginx:latest'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    networks:
      - backend1
  redis:
    image: 'redis/redis-stack'
    ports:
      - '6370:6379'
      - '8002:8001'
    networks:
      - backend1
networks:
  backend1:
    driver: bridge